name: Type Checking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tsc:
    name: Compile Safety check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run TypeScript Compiler Check
        run: npx tsc --noEmit
